### PR TITLE
Fix: README Latest Release Badge, Link

### PR DESCRIPTION
**Pull request by korenyoni**
## what
* Fix README links originating from `terraform-example-module` (latest release badge, releases link)
* add `exclude-labels` option to `auto-release.yaml`

## why
* Latest release badge, link in README is incorrect

## references
* N/A

### CODE REVIEW

**Comment by nitrocode** [comment]
This is a pretty small change. It would be more worth it to combine this with a follow up PR.

**Review by nitrocode — DISMISSED** [review]

**Comment by korenyoni** [comment]
> This is a pretty small change. It would be more worth it to combine this with a follow up PR.

I personally don't believe that PRs can be too small if they are worth having in the main branch. However I see the concern with PRs being too small in the context of Draft Releaser, so I added an [`exclude-labels` option](https://github.com/release-drafter/release-drafter#exclude-pull-requests) to `auto-release.yaml` and added the corresponding label to this branch.

See: https://github.com/cloudposse/terraform-example-module/issues/13

**Review by aknysh — APPROVED** [review]

**Review by nitrocode — APPROVED** [review]

**Comment by korenyoni** [comment]
At first I believed that simply setting exclude-labels in `.github/auto-release.yaml` will enable this. However that only skips the release from being drafted. A release will still be made because of the publish action input.

The actual solution probably involves detecting the labels in the PR and programatically setting `publish` based on that, within the `auto-release` GitHub Actions workflow.

See: https://github.com/cloudposse/terraform-example-module/issues/13

**Pull request merged**
